### ISSUE TITLE
JsonValue toString performance

### ISSUE THREAD

**Issue by huuskart** [vaadin/gwt#10]
Optimize JsonValue toString performance by avoiding temporary memory allocation and copy with strings. Also allow caller to supply StringBuilder buffer instead of forcing caller to append result.

Apologies for submitting this as an issue with patch instead of pull request.

[elemental.patch.txt](https://github.com/vaadin/gwt/files/5943412/elemental.patch.txt)

**Comment by TatuLund** [comment]
There has been a ticket about the topic in the framework. This gwt-repo is no longer actually used in our framework, so it is at the moment deprecated and it does not make sense to modify it anymore. We are using GWT via normal dependency. The right place thus would be to submit these contributions directly there. See also discussion and comments in the linked ticket

https://github.com/vaadin/framework/issues/5987
